import type { SiteConfig } from "@/lib/types";

/**
 * ┌──────────────────────────────────────────────────────────────────────────┐
 * │  THIS IS THE FILE YOU EDIT TO MAKE THE PAGE YOURS.                          │
 * │  Change the values below, drop your copy into content/landing.json, set     │
 * │  your env vars, and deploy. You should not need to touch anything in src/.  │
 * └──────────────────────────────────────────────────────────────────────────┘
 *
 * Current values: a DEMO "book a call" offer — ElevateAI's free AI Opportunity
 * Audit. Generated by the engine's own research → write → critique pipeline.
 * NOTE: the proof points / stats are PLACEHOLDERS — confirm or replace them
 * before going live (see strategy.proof below and the stats section in content).
 */
export const siteConfig: SiteConfig = {
  business: {
    name: "ElevateAI",
    legalName: "ElevateAI",
    domain: "elevateai.tech",
    supportEmail: "hello@elevateai.tech",
    phone: "",
  },

  brand: {
    colors: {
      brand: "#0F4C5C",
      brandFg: "#FFFFFF",
      brandMuted: "#E3EEF0",
      accent: "#2EC4B6",
      accentFg: "#06302C",
      bg: "#F7F9FA",
      surface: "#FFFFFF",
      ink: "#13202A",
      inkMuted: "#566570",
      line: "#DDE5E8",
      success: "#1F9E7A",
    },
    radius: "0.875rem",
    fonts: {
      sans: "Inter",
      display: "Inter",
      stylesheets: [
        "https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap",
      ],
    },
    logo: {
      src: "",
      wordmark: "ElevateAI",
    },
  },

  seo: {
    siteName: "ElevateAI",
    defaultTitle: "Free AI Opportunity Audit for SMBs",
    titleTemplate: "%s | ElevateAI",
    defaultDescription:
      "In 30 minutes, see the 3 automations worth the most hours to your business — in plain English, yours to keep. Free, no obligation, no sales pitch. For teams of 10–250.",
    defaultOgImage: "",
    twitterHandle: "",
    locale: "en_US",
    currency: "USD",
  },

  analytics: {
    // Leave blank to use the NEXT_PUBLIC_GA4_MEASUREMENT_ID env var instead.
    ga4MeasurementId: "",
    enableConsentBanner: true,
    scrollDepthThresholds: [25, 50, 75, 90],
    reportWebVitals: true,
  },

  conversion: {
    primaryGoal: "call",
    primaryCtaHref: "#lead",
    leadWebhookEnabled: true,
    conversionEventName: "generate_lead",
  },

  experiment: {
    enabled: true,
    variants: ["A", "B"],
  },

  social: {
    linkedin: "https://www.linkedin.com/company/elevateai",
  },

  organization: {
    type: "ProfessionalService",
    sameAs: ["https://www.linkedin.com/company/elevateai"],
  },

  strategy: {
    offer:
      "Free 30-minute AI Opportunity Audit for SMBs (10–250 staff). On the call, ElevateAI maps the 3 highest-payoff AI/automation use-cases for that specific business and hands over a prioritized, plain-English implementation plan the team can run itself or with ElevateAI's help. Primary on-page action is a 4-field lead form; on submit, a booking link is sent.",
    icp:
      "Owners and operations/finance leaders at small and mid-sized businesses (roughly 10–250 staff) who suspect AI could save them time and money but don't know where to start. They are skeptical of hype and agencies, have no in-house AI person, are stretched thin, and worry their data is too messy or their company too small to benefit.",
    objections: [
      "Is this just a sales pitch in disguise?",
      "We're too small / AI isn't really applicable to a business like ours.",
      "Our data is a mess, so we're not ready.",
      "We don't have anyone technical or an AI person on staff.",
      "We've been burned by AI hype and agency promises before.",
      "Where does our information go — is it private?",
      "Will this end in a pushy upsell or a $50k transformation pitch?",
      "I don't have time for another long meeting.",
    ],
    proof: [
      "PLACEHOLDER — confirm before live: Audited 40+ SMBs",
      "PLACEHOLDER — confirm before live: Most audits surface 3–5 automations worth reclaiming 5–15 hrs/week",
      "PLACEHOLDER — confirm before live: Clients typically ship their first automation within 2 weeks",
      "Free, no-obligation, no sales pitch",
    ],
    voice:
      "Confident, concrete, warm. Short sentences. Quantify the payoff in reclaimed hours, never revenue. No hype, no buzzwords, no exclamation marks in body copy. Sounds like the calm adult in a hyped room — out-credible the restrained competitors rather than out-promise the hype ones.",
    forbiddenClaims: [
      "No guaranteed revenue or ROI figures (no $ or %-ROI promises)",
      "No 'replace your staff' or 'fully autonomous' claims",
      "Never name clients or cite stats not given as allowed proof",
      "No fake certifications or partnerships",
      "No false urgency, countdown timers, or 'unlock the power of AI' buzzwords",
    ],
  },
};

export default siteConfig;
